# GoReleaser configuration for Twingate Caddy Plugin
# Builds Caddy with the Twingate plugin embedded

version: 2

builds:
  - id: caddy-twingate
    # Build Caddy with the Twingate plugin from cmd/caddy/main.go
    main: ./cmd/caddy
    binary: caddy

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - freebsd

    goarch:
      - amd64
      - arm64
      - arm

    goarm:
      - "6"
      - "7"

    # Exclude unsupported combinations
    ignore:
      - goos: freebsd
        goarch: arm
        goarm: "6"
      - goos: freebsd
        goarch: arm
        goarm: "7"
      - goos: freebsd
        goarch: arm64

    ldflags:
      - -s -w
      - -X github.com/caddyserver/caddy/v2.CustomVersion={{.Version}}

archives:
  - id: caddy-twingate-archive
    name_template: "caddy-twingate_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    # GoReleaser v2 automatically uses tar.gz for Unix and zip for Windows
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^Merge"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: EngineeredDev
    name: twingate-caddy

  # Create release draft for manual review
  draft: false
  prerelease: auto

  name_template: "{{.Tag}}"

  # Release footer
  footer: |
    ## Installation

    Download the appropriate binary for your platform and architecture.

    ### Supported Platforms
    - Linux: amd64, arm64, armv6, armv7
    - FreeBSD: amd64

# Snapshot builds for testing
snapshot:
  version_template: "{{ .Version }}-SNAPSHOT-{{ .ShortCommit }}"

# Metadata
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
